export interface Product {
  product_id: number;
  product_name: string;
  product_price: number;
  original_price: number;
  image: string;
  category: string;
  description: string;
  badge?: string;
  max_quantity: number;
  rating: number;
  reviews: number;
  tags: string[];
}

export const ALL_PRODUCTS: Product[] = [
  {
    product_id: 101,
    product_name: "Bamboo Toothbrush (Pack of 4)",
    product_price: 299,
    original_price: 399,
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&q=80",
    category: "Personal Care",
    description: "Biodegradable bamboo handle with BPA-free nylon bristles. Fully compostable after use.",
    badge: "Best Seller",
    max_quantity: 10,
    rating: 4.8,
    reviews: 312,
    tags: ["bamboo", "oral care", "compostable"],
  },
  {
    product_id: 102,
    product_name: "Reusable Cotton Produce Bags",
    product_price: 450,
    original_price: 550,
    image: "https://images.unsplash.com/photo-1610348725531-843dff563e2c?w=600&q=80",
    category: "Kitchen",
    description: "Set of 6 organic cotton mesh bags for zero-waste grocery shopping. Machine washable.",
    badge: "New",
    max_quantity: 15,
    rating: 4.6,
    reviews: 188,
    tags: ["cotton", "zero waste", "grocery"],
  },
  {
    product_id: 103,
    product_name: "Stainless Steel Water Bottle (1L)",
    product_price: 799,
    original_price: 999,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    category: "Kitchen",
    description: "Double-walled vacuum insulated. Keeps cold 24h & hot 12h. Leak-proof lid.",
    badge: "Top Rated",
    max_quantity: 8,
    rating: 4.9,
    reviews: 521,
    tags: ["steel", "insulated", "BPA-free"],
  },
  {
    product_id: 104,
    product_name: "Beeswax Food Wraps (Set of 3)",
    product_price: 399,
    original_price: 499,
    image: "https://images.unsplash.com/photo-1585559700398-1385b3a8aeb6?w=600&q=80",
    category: "Kitchen",
    description: "Reusable, washable alternative to plastic wrap. Made with organic cotton & beeswax.",
    max_quantity: 20,
    rating: 4.5,
    reviews: 97,
    tags: ["beeswax", "plastic-free", "food storage"],
  },
  {
    product_id: 105,
    product_name: "Organic Neem Wood Comb",
    product_price: 149,
    original_price: 199,
    image: "https://images.unsplash.com/photo-1526045612212-70caf35c14df?w=600&q=80",
    category: "Personal Care",
    description: "Hand-carved neem wood comb. Naturally anti-bacterial, anti-dandruff & static-free.",
    max_quantity: 25,
    rating: 4.4,
    reviews: 74,
    tags: ["neem", "handmade", "hair care"],
  },
  {
    product_id: 106,
    product_name: "Coconut Shell Bowls (Set of 4)",
    product_price: 599,
    original_price: 750,
    image: "https://images.unsplash.com/photo-1603569283847-aa295f0d016a?w=600&q=80",
    category: "Kitchen",
    description: "Handcrafted coconut shell bowls with wooden spoons. Perfect for smoothie bowls.",
    badge: "Handmade",
    max_quantity: 12,
    rating: 4.7,
    reviews: 143,
    tags: ["coconut", "handcrafted", "bowls"],
  },
  {
    product_id: 107,
    product_name: "Recycled Paper Notebook (A5)",
    product_price: 249,
    original_price: 299,
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=600&q=80",
    category: "Stationery",
    description: "100% post-consumer recycled paper, soy-based ink. 200 ruled pages.",
    max_quantity: 30,
    rating: 4.3,
    reviews: 56,
    tags: ["recycled", "notebook", "soy ink"],
  },
  {
    product_id: 108,
    product_name: "Jute Shopping Bag",
    product_price: 199,
    original_price: 249,
    image: "https://images.unsplash.com/photo-1593810451137-5dc55105dace?w=600&q=80",
    category: "Lifestyle",
    description: "Sturdy reusable natural jute bag with reinforced handles. Holds up to 15kg.",
    badge: "Eco Pick",
    max_quantity: 20,
    rating: 4.6,
    reviews: 208,
    tags: ["jute", "tote", "reusable"],
  },
  {
    product_id: 109,
    product_name: "Bamboo Cutlery Set",
    product_price: 349,
    original_price: 449,
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=600&q=80",
    category: "Kitchen",
    description: "Fork, knife, spoon & chopsticks in a hand-stitched linen pouch. Travel-ready.",
    max_quantity: 18,
    rating: 4.5,
    reviews: 132,
    tags: ["bamboo", "travel", "utensils"],
  },
  {
    product_id: 110,
    product_name: "Natural Loofah Sponge (Pack of 2)",
    product_price: 179,
    original_price: 229,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    category: "Personal Care",
    description: "100% natural plant-based loofah. Exfoliates, cleanses. Fully compostable.",
    max_quantity: 40,
    rating: 4.2,
    reviews: 88,
    tags: ["loofah", "exfoliating", "compostable"],
  },
  {
    product_id: 111,
    product_name: "Seed Paper Greeting Cards (Pack of 5)",
    product_price: 299,
    original_price: 349,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    category: "Stationery",
    description: "Plant these cards after use — wildflower seeds embedded inside. Zero waste gifting.",
    badge: "Unique Gift",
    max_quantity: 15,
    rating: 4.8,
    reviews: 267,
    tags: ["seed paper", "plantable", "gifting"],
  },
  {
    product_id: 112,
    product_name: "Solar Lantern (Portable)",
    product_price: 1299,
    original_price: 1599,
    image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&q=80",
    category: "Lifestyle",
    description: "Foldable solar-powered LED lantern. 6h charge → 12h light. USB backup charging.",
    badge: "Premium",
    max_quantity: 5,
    rating: 4.9,
    reviews: 342,
    tags: ["solar", "LED", "camping"],
  },
];

export const CATEGORIES = ["All", "Kitchen", "Personal Care", "Lifestyle", "Stationery"];
